---
- hosts: all
  gather_facts: False
  vars:
    http_port: 80
    max_clients: 200
  become: yes
  tasks:
  # - name: ensure apache is at the latest version
  #   apt:
  #     name: apache2
  #     state: latest
  # - name: write the apache config file
  #   template:
  #     src: apache2.j2
  #     dest: /etc/apache2.conf
  #   notify:
  #   - restart apache
  # - name: ensure apache is running - (and enable it at boot)
  #   service:
  #     name: apache2
  #     state: started
  #     enabled: yes
  - name: check webpage md5
    get_url:
      url: http://10.2.78.104/index.html
      dest: /tmp/index.html
      checksum: md5:e2620d4a5a0f8d80dd4b16de59af981f
    register: output
  - debug:
      var: output
  # handlers:
  #   - name: restart apache
  #     service:
  #       name: apache2
  #       state: restarted