---
- hosts: meiner
  vars:
    http_port: 80
    max_clients: 200
  become: yes
  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
  # - name: write the apache config file
  #   template:
  #     src: apache2.j2
  #     dest: /etc/apache2.conf
  #   notify:
  #   - restart apache
  - name: ensure apache is running (and enable it at boot)
    service:
      name: apache2
      state: started
      enabled: yes
  # handlers:
  #   - name: restart apache
  #     service:
  #       name: apache2
  #       state: restarted